In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px
import warnings 

warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_csv("travel.csv")

In [3]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [4]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [5]:
df['Gender'].value_counts() # checking for the spelling mistakes

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [6]:
#Above the female spelling is mistyped to fe male so we have to correct this

In [7]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [8]:
df["TypeofContact"].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [9]:
df["Gender"] = df["Gender"].replace('Fe Male','Female')
df["MaritalStatus"] =df["MaritalStatus"].replace("Single","Unmarried")

In [10]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [11]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [12]:
#checking missing values 
features_with_na = [features for features in df.columns if df[features].isnull().sum() >= 1]
for feature in features_with_na :
    print(feature,np.round(df[feature].isnull().mean()*100,5)," % missing values ")

Age 4.62357  % missing values
TypeofContact 0.51146  % missing values
DurationOfPitch 5.13502  % missing values
NumberOfFollowups 0.92062  % missing values
PreferredPropertyStar 0.53191  % missing values
NumberOfTrips 2.86416  % missing values
NumberOfChildrenVisiting 1.35025  % missing values
MonthlyIncome 4.76678  % missing values

In [13]:
df[features_with_na].select_dtypes(exclude = 'object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [14]:
# imputing null valaues 
df.Age.fillna(df.Age.median(), inplace = True)

df.TypeofContact.fillna(df.TypeofContact.mode()[0], inplace = True) 

df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace = True)

df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0], inplace = True) 

df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0], inplace = True)

df.NumberOfTrips.fillna(0, inplace = True)

df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0], inplace = True)

df.MonthlyIncome.fillna(df.MonthlyIncome.median() , inplace = True)

In [15]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [16]:
df.drop("CustomerID", inplace = True , axis = 1)

In [17]:
df['TotalVisiting'] = df["NumberOfPersonVisiting"] + df["NumberOfChildrenVisiting"]

In [18]:
df.drop(columns = ['NumberOfPersonVisiting',"NumberOfChildrenVisiting"], axis=1 , inplace  = True)

In [19]:
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))

Num of Numerical Features : 12

In [20]:
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('num of contigorical features : ', len(cat_features))

num of contigorical features :  6

In [21]:
discrete_features = [feature for feature in num_features if len(df[feature].unique()) <= 25] 
print('num of discrete features : ', len(discrete_features))

num of discrete features :  9

In [22]:
continouse_feature = [feature for feature in num_features if feature not in discrete_features]
print('num of continous features : ', len(continouse_feature))

num of continous features :  3

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X = df.drop(["ProdTaken"],axis=1)
y = df['ProdTaken']

In [25]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [26]:
X.head()

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [27]:
X_train, X_test , y_train , y_test  = train_test_split(X,y, test_size = 0.2, random_state = 5)
X_train.shape , X_test.shape

((3910, 17), (978, 17))

In [28]:
cat_features = X.select_dtypes(include="object").columns 
num_features = X.select_dtypes(exclude="object").columns

In [29]:
from sklearn.preprocessing import OneHotEncoder , StandardScaler 
from sklearn.compose import ColumnTransformer
numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop = "first")

In [30]:
preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features)
    ]
)

In [31]:
##applying transformation in training(fit_transform)
X_train = preprocessor.fit_transform(X_train)

In [32]:
X_test = preprocessor.transform(X_test)

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.linear_model import LogisticRegression

In [34]:
models = {
    "Logistic Regression" : LogisticRegression(),
    "Decision Tree" : DecisionTreeClassifier(),
    "Random Forest" : RandomForestClassifier()    
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    print("** train data **")
    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1 = f1_score(y_train, y_train_pred, average = "weighted")
    model_train_precision = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train ,y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train, y_train_pred)

    print(model_train_accuracy,model_train_f1,model_train_precision,model_train_recall,model_train_rocauc_score)

    print("** test data **")

    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1 = f1_score(y_test, y_test_pred, average = "weighted")
    model_test_precision = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test ,y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test, y_test_pred)

    print(model_test_accuracy ,model_test_f1, model_test_precision ,model_test_recall,model_test_rocauc_score)
    print(list(models.keys())[i])

** train data **
0.8460358056265984 0.8203163765955388 0.715625 0.30945945945945946 0.6403764174268907
** test data **
0.8486707566462167 0.8225608985925659 0.7105263157894737 0.3 0.6362155388471178
Logistic Regression
** train data **
1.0 1.0 1.0 1.0 1.0
** test data **
0.9100204498977505 0.9107718397450068 0.7446808510638298 0.7777777777777778 0.858813700918964
Decision Tree
** train data **
1.0 1.0 1.0 1.0 1.0
** test data **
0.9376278118609407 0.933246235964011 0.968503937007874 0.6833333333333333 0.8391604010025062
Random Forest

In [35]:
 #hyperparameter Tunning 
rf_params = {
    "max_depth" : [5,8,15,None,10],
    "max_features" : [5,7,"auto", 8],
    "min_samples_split" : [2,8,15,20],
    "n_estimators" : [100 ,200, 500,1000]
    
}

In [36]:
randomcv_models = [
    ("RF" , RandomForestClassifier(), rf_params),
]

In [37]:
randomcv_models

[('RF',
  RandomForestClassifier(),
  {'max_depth': [5, 8, 15, None, 10],
   'max_features': [5, 7, 'auto', 8],
   'min_samples_split': [2, 8, 15, 20],
   'n_estimators': [100, 200, 500, 1000]})]

In [40]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {} 
for name, model , params in randomcv_models:
    random = RandomizedSearchCV(estimator = model , param_distributions = params ,
                               n_iter = 100 , 
                               cv = 3,
                               verbose=2,
                               n_jobs = -1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"------best params for {model_name}--------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
------best params for RF--------
{'n_estimators': 1000, 'min_samples_split': 2, 'max_features': 8, 'max_depth': None}

In [42]:
models = {
    "Random Forest" : RandomForestClassifier(n_estimators = 1000, min_samples_split = 2,max_depth = None , max_features = 7)
    
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    print("** train data **")
    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1 = f1_score(y_train, y_train_pred, average = "weighted")
    model_train_precision = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train ,y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train, y_train_pred)

    print(model_train_accuracy,model_train_f1,model_train_precision,model_train_recall,model_train_rocauc_score)

    print("** test data **")

    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1 = f1_score(y_test, y_test_pred, average = "weighted")
    model_test_precision = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test ,y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test, y_test_pred)

    print(model_test_accuracy ,model_test_f1, model_test_precision ,model_test_recall,model_test_rocauc_score)
    print(list(models.keys())[i])

** train data **
1.0 1.0 1.0 1.0 1.0
** test data **
0.9468302658486708 0.9443111740096362 0.9507042253521126 0.75 0.8706140350877193
Random Forest

In [44]:
!git --version

git version 2.51.1.windows.1

In [46]:
!cd

C:\Users\adity\machine learning

In [47]:
!git init

Initialized empty Git repository in C:/Users/adity/machine learning/.git/

In [48]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Travel.csv
	decisiontreeimplimentation.ipynb
	handling categorical data.ipynb
	handling mixed values .ipynb
	handlingdata and timevariable.ipynb
	height-weight.csv
	heightWieghtpredictor.ipynb
	housing dataset.csv
	mean median imputation .ipynb
	messages.csv
	orders.csv
	placement.csv
	randomForest.ipynb
	simpleLinear-scratch.ipynb
	titanic.csv
	train.csv
	wine_data.csv

nothing added to commit but untracked files present (use "git add" to track)

In [49]:
!git add randomForest.ipynb

warning: in the working copy of 'randomForest.ipynb', LF will be replaced by CRLF the next time Git touches it

In [51]:
!git commit -m "Added randomforest notebook"

[master (root-commit) 7fd75f0] Added randomforest notebook
 1 file changed, 1401 insertions(+)
 create mode 100644 randomForest.ipynb

In [53]:
!git remote add origin https://github.com/Adityadev1oper/machine-learning-Algorithms.git

In [56]:
!git push -u origin master

branch 'master' set up to track 'origin/master'.

remote:
remote: Create a pull request for 'master' on GitHub by visiting:
remote:      https://github.com/Adityadev1oper/machine-learning-Algorithms/pull/new/master
remote:
To https://github.com/Adityadev1oper/machine-learning-Algorithms.git
 * [new branch]      master -> master

In [57]:
!git push

Everything up-to-date

In [58]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   randomForest.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Travel.csv
	decisiontreeimplimentation.ipynb
	handling categorical data.ipynb
	handling mixed values .ipynb
	handlingdata and timevariable.ipynb
	height-weight.csv
	heightWieghtpredictor.ipynb
	housing dataset.csv
	mean median imputation .ipynb
	messages.csv
	orders.csv
	placement.csv
	simpleLinear-scratch.ipynb
	titanic.csv
	train.csv
	wine_data.csv

no changes added to commit (use "git add" and/or "git commit -a")

In [60]:
!git status
!git log --online -3 
!git remote -v

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   randomForest.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Travel.csv
	decisiontreeimplimentation.ipynb
	handling categorical data.ipynb
	handling mixed values .ipynb
	handlingdata and timevariable.ipynb
	height-weight.csv
	heightWieghtpredictor.ipynb
	housing dataset.csv
	mean median imputation .ipynb
	messages.csv
	orders.csv
	placement.csv
	simpleLinear-scratch.ipynb
	titanic.csv
	train.csv
	wine_data.csv

no changes added to commit (use "git add" and/or "git commit -a")

fatal: unrecognized argument: --online

origin	https://github.com/Adityadev1oper/machine-learning-Algorithms.git (fetch)
origin	https://github.com/Adityadev1oper/machine-learning-Algorithms.git (push)